name: build calendars

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: initialize
        run: |
          sudo apt-get install -y jq moreutils sqlite3
      - name: build
        run: |
          ./outage
      - name: upload
        uses: actions/upload-artifact@v7
        with:
          name: calendars
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download
        uses: actions/download-artifact@v8
        with:
          name: calendars
          path: ./out
      - name: deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
